import PageWrapper from "../components/PageWrapper";

export default function WhyDistance() {
  return (
    <PageWrapper>
      <div className="max-w-4xl mx-auto px-6 py-24 text-gray-200">

        <h1 className="text-4xl md:text-5xl text-cyan-300 font-semibold mb-10 text-center">
          Why Distance Is Not a Barrier
        </h1>

        <p className="leading-relaxed mb-8 text-center text-gray-300">
          This explanation does not require belief.  
          It requires only observation, physiology, and attention.
        </p>

        <section className="space-y-6 leading-relaxed text-sm sm:text-base md:text-lg">
          <p>
            Human experience is mediated through the nervous system. Sensation,
            emotion, breath, and awareness are internally generated processes.
            They are not transmitted objects, but responses arising within the
            body when attention is directed in specific ways.
          </p>

          <p>
            In this context, physical proximity is not a prerequisite. Guidance,
            language, tone, pacing, and focused attention are sufficient to
            influence internal regulation — just as reading, listening, or
            observing can alter breathing patterns or emotional states.
          </p>

          <p>
            Distance-based sessions do not attempt to “send” anything. They
            simply create structured conditions in which awareness is invited
            inward. Any resulting experience is self-generated by the client’s
            own nervous system.
          </p>

          <p>
            Ancient healing traditions recognised this long before modern
            terminology existed. Contemporary language sometimes references
            “quantum” or “non-local” ideas symbolically, not as physics claims,
            but as metaphors for subtle, non-mechanical interaction.
          </p>

          <p className="text-gray-400 italic text-sm">
            This work does not depend on belief, suggestion, or interpretation.
            It depends on attention, safety, and internal perception.
          </p>
        </section>

        <p className="mt-12 text-center italic text-cyan-300">
          Distance changes location — not awareness.
        </p>
      </div>
    </PageWrapper>
  );
}
